{% set name = "pycirclize" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycirclize-{{ version }}.tar.gz
  sha256: 6577760657886c06bcfab63f1c69def28de7a8c3e8af8d56042857f1ac14dc6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - biopython >=1.80
    - matplotlib-base >=3.6.3
    - numpy >=1.21.1
    - pandas >=1.3.5

test:
  imports:
    - pycirclize
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://moshi4.github.io/pyCirclize/
  summary: Circular visualization in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moshi4
