{% set name = "pycirclize" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycirclize-{{ version }}.tar.gz
  sha256: 0ffb3a408cef3bb159d59d6a78266f2ee1dae2dda93e7ef5a5662be711ddf1ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry
    - pip
  run:
    - python >=3.8
    - biopython >=1.79
    - matplotlib-base >=3.5.2
    - numpy >=1.21.1
    - pandas >=1.3.5

test:
  imports:
    - pycirclize
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
  source_files:
    - tests/

about:
  home: https://moshi4.github.io/pyCirclize/
  summary: Circular visualization in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moshi4
